FROM python:3.12-slim AS uv-build

# Create and activate venv
WORKDIR /app
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Install dependencies
COPY app/ /app/
RUN pip install --no-cache-dir uv && \
    uv pip install -r requirements.txt

CMD ["python", "main.py"]
