FROM python:3.12-slim AS uv-build

# Install curl first, then uv
RUN apt-get update && apt-get install -y curl && \
    curl -LsSf https://astral.sh/uv/install.sh | sh && \
    # mv ~/.cargo/bin/uv /usr/local/bin/uv && \
    mv /root/.local/bin/uv /usr/local/bin/uv && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY app/ /app/

RUN uv pip install --system -r requirements.txt
CMD ["python", "main.py"]
