version: "3.9"

services:
  graphql-pip:
    build:
      context: .
      dockerfile: Dockerfile.pip
    container_name: graphql_pip
    ports:
      - "8001:8000"

  graphql-uv:
    build:
      context: .
      dockerfile: Dockerfile.uv
    container_name: graphql_uv
    ports:
      - "8002:8000"
